#!/bin/sh

### BEGIN INIT INFO
# Provides:          Vespucci SADServer
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:  Starts the Vespucci SADServer, does not stop it gracefully, but the database has its own hook.
# Description: To be placed in /etc/init.d then registered there with "sudo update-rc.d sadserver defaults 99"
### END INIT INFO
# Author: Mateusz Parzonka <parzonka@gmail.com>


# Handle manual control parameters like start, stop, status, restart, etc.

case "$1" in
    start)
        echo "Starting SADServer"
        cd /opt/sadserver
        java -jar sadserver.jar
        ;;
    stop)
        echo "Stopping SADServer"
        ;;
    restart)
        echo "Starting SADServer"
        cd /opt/sadserver
        java -jar sadserver.jar
        ;;
esac

exit 0
