<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="global_repository"
    nsURI="http://global-repository" nsPrefix="vespucci">
  <eClassifiers xsi:type="ecore:EClass" name="GlobalRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembles" ordered="false"
        upperBound="-1" eType="ecore:EClass vespucci.ecore#//Ensemble" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
